apiVersion: v1
kind: Service
metadata:
  name: taskflow-api
  namespace: taskflow
spec:
  type: NodePort           # para podermos usar o Tailscale Funnel depois
  selector:
    app: taskflow-api
  ports:
  - port: 80              # porta interna do Service
    targetPort: 8080      # porta do container
    nodePort: 30080       # porta no nó (Raspberry Pi) — ajuste se quiser outra
