services:
  taskflow-api:
    build:
      context: .
      dockerfile: Dockerfile
      # platform: linux/arm/v7  # Remova ou comente esta linha
    image: brunomano/taskflow-api:latest
    # platform: linux/arm/v7  # Remova ou comente esta linha
    ports:
      - "8080:8080"
    restart: always
